# **************************************************************************** #
#                                                                              #
#                                                            ____    _____     #
#    Makefile                                               |___ \  |___ /     #
#                                                             __) |   |_ \     #
#    By: shobeedev <https://shobee.space/>                   / __/   ___) |    #
#                                                           |_____| |____/     #
#    Created: 2025/12/29 20:06:03 by shobeedev               shobee4ever       #
#    Updated: 2025/12/29 20:11:02 by shobeedev            tfaaty fi l3oolaa    #
#                                                                              #
# **************************************************************************** #


app :
	g++ number.cpp ../src/number/number.cpp  -o testprog
clean :
	rm -rf *.out testprog *.o
