# **************************************************************************** #
#                                                                              #
#                                                            ____    _____     #
#    Makefile                                               |___ \  |___ /     #
#                                                             __) |   |_ \     #
#    By: shobeedev <https://shobee.space/>                   / __/   ___) |    #
#                                                           |_____| |____/     #
#    Created: 2025/12/29 20:06:03 by shobeedev               shobee4ever       #
#    Updated: 2025/12/31 18:38:53 by shobeedev            tfaaty fi l3oolaa    #
#                                                                              #
# **************************************************************************** #

app : ../../src/number/number.o
	@g++ main.cpp ../../src/number/number.o  -o testprog
	@echo "The executable file is ready."
clean :
	@rm -rf *.out testprog
	@rm -rf ../../src/number/number.o
	@echo "Done"
