# **************************************************************************** #
#                                                                              #
#                                                            ____    _____     #
#    Makefile                                               |___ \  |___ /     #
#                                                             __) |   |_ \     #
#    By: shobeedev <https://shobee.space/>                   / __/   ___) |    #
#                                                           |_____| |____/     #
#    Created: 2025/12/31 18:42:20 by shobeedev               shobee4ever       #
#    Updated: 2025/12/31 18:44:37 by shobeedev            tfaaty fi l3oolaa    #
#                                                                              #
# **************************************************************************** #

all : ../../src/math/math.o
	g++ main.cpp ../../src/math/math.o -o testprog

clean :
	rm -rf testprog
	rm -rf ../../src/math/math.o

