# **************************************************************************** #
#                                                                              #
#                                                            ____    _____     #
#    Makefile                                               |___ \  |___ /     #
#                                                             __) |   |_ \     #
#    By: shobeedev <https://shobee.space/>                   / __/   ___) |    #
#                                                           |_____| |____/     #
#    Created: 2026/01/02 19:35:20 by shobeedev               shobee4ever       #
#    Updated: 2026/01/02 19:39:37 by shobeedev            tfaaty fi l3oolaa    #
#                                                                              #
# **************************************************************************** #

app : ../../src/random/random.o
	g++ test.cpp ../../src/random/random.o -o testprog

clean :
	rm -rf testprog
	rm -rf ../../src/random/random.o
